### PR TITLE
Application test

### PR DESCRIPTION
**Pull request by astropiuu**
## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.rst`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [ ] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Review by prithviulm — CHANGES_REQUESTED** [review]
Looks good. Remove the egg_info directories though. They have been included in the gitignore recently but I think you were already tracking them in git before updating the gitignore (git doesn't retroactively untrack files). I think you have to clear the git cache or so to force it ti stop tracking them

**Review by prithviulm — APPROVED** [review]

**Comment by prithviulm** [comment]
The tests are failing at the setup. Can you have a look at it?

**Review by prithviulm — CHANGES_REQUESTED** [review]
Tests fail during setup. Can you have a look at it?

**Comment by astropiuu** [comment]
> Tests fail during setup. Can you have a look at it?

Yes, the linux has some issues with qt plugins. I'm making small changes and try trial and error. Do you have any idea about this?

**Comment by prithviulm** [comment]
Let's discuss tmr. Seems to be a namespace issue again

**Pull request merged**
